# Generated by Django 5.1.6 on 2025-03-30 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', 'new_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='secondary_language',
        ),
    ]
