# Generated by Django 5.1.7 on 2025-04-02 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='adminapp.cart'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.product'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='selected_language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.language'),
        ),
        migrations.AlterModelTable(
            name='cartitem',
            table='userapp_cartitem',
        ),
    ]
