# Generated by Django 5.1.6 on 2025-03-05 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_customuser_address_customuser_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='state',
        ),
    ]
