# Generated by Django 5.1.6 on 2025-03-20 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_remove_orderitem_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='return_requested',
            field=models.BooleanField(default=False),
        ),
    ]
