# Generated by Django 5.1.6 on 2025-03-21 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0010_couponusage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CouponUsage',
        ),
    ]
