# Generated by Django 5.1.6 on 2025-03-14 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0016_orderitem_return_requested_orderitem_return_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='items',
            field=models.ManyToManyField(related_name='return_requests', to='adminapp.orderitem'),
        ),
    ]
