# Generated by Django 5.1.6 on 2025-03-21 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0017_remove_orderitem_returned_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
