# Generated by Django 5.1.6 on 2025-03-14 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0018_remove_orderitem_total_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='items',
            field=models.ManyToManyField(related_name='return_requests', to='adminapp.orderitem'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='return_status',
            field=models.CharField(choices=[('none', 'No Return'), ('requested', 'Return Requested'), ('approved', 'Return Approved'), ('rejected', 'Return Rejected')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_request', to='adminapp.order'),
        ),
    ]
