# Generated by Django 5.1.6 on 2025-03-15 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0019_orderitem_total_price_returnrequest_items_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnrequest',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='reason',
            field=models.CharField(choices=[('defective', 'Product is defective'), ('wrong_item', 'Received wrong item'), ('not_as_described', 'Product not as described'), ('damaged', 'Product is damaged'), ('other', 'Other')], max_length=50),
        ),
    ]
