# Generated by Django 5.1.6 on 2025-03-15 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0021_alter_orderitem_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnrequest',
            name='items',
        ),
    ]
