# Generated by Django 5.1.6 on 2025-03-22 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0024_alter_order_return_action_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='return_action',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='return_action',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
