# Generated by Django 5.1.6 on 2025-03-29 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0027_cart_coupon_alter_cart_user_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnrequest',
            name='admin_notes',
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_request', to='adminapp.orderitem'),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='comments',
            field=models.TextField(default='No comments provided'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='reason',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
