# Generated by Django 5.1.6 on 2025-03-19 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0027_product_discount_product_offer_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='offer_price',
        ),
    ]
