# Generated by Django 5.1.6 on 2025-03-29 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0030_alter_returnrequest_order_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='returnrequest',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='return_reason',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='return_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_request', to='adminapp.order'),
        ),
    ]
