# Generated by Django 5.1.6 on 2025-03-29 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0036_product_secondary_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='secondary_language',
        ),
        migrations.AddField(
            model_name='product',
            name='additional_languages',
            field=models.ManyToManyField(blank=True, related_name='additional_products', to='adminapp.language'),
        ),
    ]
