# Generated by Django 5.1.6 on 2025-03-29 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0037_remove_product_secondary_language_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='additional_languages',
        ),
        migrations.AddField(
            model_name='product',
            name='second_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondary_products', to='adminapp.language'),
        ),
        migrations.AddField(
            model_name='product',
            name='third_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tertiary_products', to='adminapp.language'),
        ),
        migrations.AlterField(
            model_name='product',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_products', to='adminapp.language'),
        ),
    ]
