# Generated by Django 5.1.6 on 2025-03-29 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0039_remove_product_third_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='second_language',
        ),
        migrations.AlterField(
            model_name='product',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.language'),
        ),
    ]
