# Generated by Django 5.1.6 on 2025-03-29 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0041_remove_product_language_product_languages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='languages',
        ),
        migrations.AddField(
            model_name='product',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.language'),
        ),
        migrations.AddField(
            model_name='product',
            name='secondary_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondary_products', to='adminapp.language'),
        ),
    ]
