# Generated by Django 5.1.6 on 2025-03-29 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0042_remove_product_languages_product_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='selected_language',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.language'),
            preserve_default=True,
        ),
    ]
