# Generated by Django 5.1.6 on 2025-03-30 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0046_remove_product_language_product_primary_language_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='primary_language',
        ),
        migrations.RemoveField(
            model_name='product',
            name='secondary_language',
        ),
        migrations.AddField(
            model_name='product',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.language'),
        ),
    ]
