# Generated by Django 5.1.6 on 2025-03-30 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0048_product_secondary_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.language'),
        ),
    ]
