# Generated by Django 5.1.6 on 2025-03-30 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_remove_product_secondary_language'),
        ('adminapp', '0049_alter_product_language'),
    ]

    operations = [
    ]
