# Generated by Django 5.1.7 on 2025-04-01 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0055_remove_language_added_on_alter_language_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_cart_items', to='adminapp.product'),
        ),
    ]
