# Generated by Django 5.1.7 on 2025-04-01 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0059_remove_orderitem_selected_language_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallettransaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='wallettransaction',
            old_name='date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='wallettransaction',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='wallettransaction',
            name='type',
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.order'),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit')], default='credit', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
