# Generated by Django 5.1.7 on 2025-04-01 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
    ]
