# Generated by Django 5.1.7 on 2025-04-01 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_auto_20250401_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='primary_language',
        ),
        migrations.RemoveField(
            model_name='product',
            name='secondary_language',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tertiary_language',
        ),
        migrations.AddField(
            model_name='product',
            name='languages',
            field=models.ManyToManyField(blank=True, related_name='products', to='adminapp.language'),
        ),
    ]
