# Generated by Django 5.1.6 on 2025-03-21 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0014_remove_returnrequest_admin_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnrequest',
            name='comments',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='adminapp.order'),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='reason',
            field=models.CharField(choices=[('defective', 'Product is defective'), ('wrong_item', 'Received wrong item'), ('not_as_described', 'Product not as described'), ('damaged', 'Product is damaged'), ('other', 'Other')], max_length=50),
        ),
    ]
