# Generated by Django 5.1.6 on 2025-03-22 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0020_wallet_wallettransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='return_action',
            field=models.CharField(choices=[('none', 'None'), ('return_requested', 'Return Requested'), ('return_accepted', 'Return Accepted'), ('return_rejected', 'Return Rejected')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='return_action',
            field=models.CharField(choices=[('none', 'None'), ('return_requested', 'Return Requested'), ('return_accepted', 'Return Accepted'), ('return_rejected', 'Return Rejected')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Returned')], default='pending', max_length=20),
        ),
    ]
