# Generated by Django 5.1.6 on 2025-03-22 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0023_alter_order_return_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='return_action',
            field=models.CharField(choices=[('none', 'None'), ('Return', 'Return'), ('Return Approved', 'Return Approved'), ('Return Rejected', 'Return Rejected')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('return_requested', 'Return Requested'), ('return_approved', 'Return Approved'), ('return_rejected', 'Return Rejected'), ('returned', 'Returned')], default='pending', max_length=20),
        ),
    ]
