# Generated by Django 5.1.6 on 2025-03-29 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0028_remove_returnrequest_admin_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='admin_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='reason',
            field=models.CharField(choices=[('defective', 'Product is defective'), ('wrong_item', 'Received wrong item'), ('not_as_described', 'Product not as described'), ('damaged', 'Product is damaged'), ('other', 'Other')], max_length=50),
        ),
    ]
