# Generated by Django 5.1.6 on 2025-03-29 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0029_returnrequest_admin_notes_alter_returnrequest_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnrequest',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='adminapp.order'),
        ),
        migrations.AlterUniqueTogether(
            name='returnrequest',
            unique_together={('order', 'order_item')},
        ),
    ]
