# Generated by Django 5.1.6 on 2025-03-29 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0040_remove_product_second_language_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='language',
        ),
        migrations.AddField(
            model_name='product',
            name='languages',
            field=models.ManyToManyField(blank=True, related_name='products', to='adminapp.language'),
        ),
    ]
