# Generated by Django 5.1.6 on 2025-03-29 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0043_cartitem_selected_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='selected_language',
        ),
    ]
