# Generated by Django 5.1.6 on 2025-03-30 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0047_remove_product_primary_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='secondary_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondary_products', to='adminapp.language'),
        ),
    ]
