# Generated by Django 5.1.6 on 2025-03-31 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0050_merge_20250330_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.language'),
        ),
    ]
