# Generated by Django 5.1.6 on 2025-03-31 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0049_add_product_language'),
        ('adminapp', '0051_alter_product_language'),
    ]

    operations = [
    ]
