# Generated by Django 5.1.6 on 2025-03-31 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0052_merge_20250331_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='language',
        ),
        migrations.AddField(
            model_name='product',
            name='primary_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_products', to='adminapp.language'),
        ),
        migrations.AddField(
            model_name='product',
            name='secondary_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondary_products', to='adminapp.language'),
        ),
        migrations.AddField(
            model_name='product',
            name='tertiary_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tertiary_products', to='adminapp.language'),
        ),
    ]
