# Generated by Django 5.1.6 on 2025-04-01 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0053_remove_product_language_product_primary_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True),
            
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='primary_language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_products', to='adminapp.language'),
        ),
        migrations.AlterField(
            model_name='product',
            name='secondary_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_products', to='adminapp.language'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tertiary_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tertiary_products', to='adminapp.language'),
        ),
    ]
